DatasetAttribution:
  - "Â© by Brockmann Consult GmbH 2025"

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: deep-esdl-team-storage
    StoreId: s3
    StoreParams:
      root: hub-deepesdl58
      storage_options:
          anon: false
          key: $S3_USER_STORAGE_KEY
          secret: $S3_USER_STORAGE_SECRET
    Datasets:
      - Identifier: sen2l2a_cube
        Path: "sen2_l2a.levels"
        Title: Sentinel-2 L2A
        Style: S2L2A
      - Identifier: oc_nws_cmems
        Path: "oc_nws_cmems.zarr"
        Title: CMEMS OC North-West Shelf 100m
        Style: CMEMS
      - Identifier: oc_glo_cmems_4km
        Path: "oc_glo_cmems_4km.zarr"
        Title: CMEMS OC L4 Global 4km
        Style: CMEMS
      - Identifier: oc_glo_cmems_300m
        Path: "oc_glo_cmems_300m.zarr"
        Title: CMEMS OC L3 Global 300m
        Style: CMEMS
      - Identifier: oc_cci
        Path: "oc_cci.zarr"
        Title: OC CCI Global
        

Styles:
  - Identifier: S2L2A
    ColorMappings:
      B02_mean:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B03_mean:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B04_mean:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B08_mean:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      scl_mean:
        ColorBar: sen2_l2a_scl
      rgb:
        Red:
          Variable: B04_mean
          ValueRange: [0., 0.25]
        Green:
          Variable: B03_mean
          ValueRange: [0., 0.25]
        Blue:
          Variable: B02_mean
          ValueRange: [0., 0.25]
  - Identifier: CMEMS
    ColorMappings:
      CHL_mean:
        ColorBar: "Greens"
        ValueRange: [0., 8.]


CustomColorMaps:
  - Identifier: sen2_l2a_scl
    Type: categorical
    Colors:
      - [0, "#000000", No Data (Missing data)]
      - [1, "#ff0000", Saturated or defective pixel]
      - [2, "#2f2f2f", Topographic casted shadows]
      - [3, "#643200", Cloud shadows]
      - [4, "#00a000", Vegetation]
      - [5, "#ffe65a", Not-vegetated]
      - [6, "#0000ff", Water]
      - [7, "#808080", Unclassified]
      - [8, "#c0c0c0", Cloud medium probability]
      - [9, "#ffffff", Cloud high probability]
      - [10, "#64c8ff", Thin cirrus]
      - [11, "#ff96ff", Snow or ice]

ServiceProvider:
  ProviderName: Brockmann Consult GmbH
  ProviderSite: https://www.brockmann-consult.de
  ServiceContact:
    IndividualName: Konstantin Ntokas
    PositionName: Software Engineer
    ContactInfo:
      Address:
        DeliveryPoint: Chrysanderstr. 1
        City: Hamburg
        AdministrativeArea: Hamburg
        PostalCode: 21029
        Country: Germany
        ElectronicMailAddress: info@brockmann-consult.de