DatasetAttribution:
  - "Â© by Brockmann Consult GmbH 2025"

DatasetChunkCacheSize: 100M

DataStores:
  - Identifier: deep-esdl-team-storage
    StoreId: s3
    StoreParams:
      root: hub-deepesdl58
      storage_options:
          anon: false
          key: $S3_USER_STORAGE_KEY
          secret: $S3_USER_STORAGE_SECRET
    Datasets:
      - Identifier: sen2l2a_cube
        Path: "sen2_l2a.levels"
        Title: Sentinel-2 L2A
        Style: S2L2A
      - Identifier: oc_nws_cmems_l3
        Path: "oc_nws_l3_cmems.zarr"
        Title: CMEMS OC L3 North-West Shelf 100m
        Style: CMEMS
      - Identifier: oc_glo_cmems_4km
        Path: "oc_glo_cmems_4km.zarr"
        Title: CMEMS OC L4 Global 4km
        Style: CMEMS
      - Identifier: oc_glo_cmems_300m
        Path: "oc_glo_cmems_300m.zarr"
        Title: CMEMS OC L3 Global 300m
        Style: CMEMS
      - Identifier: oc_cci
        Path: "oc_cci.zarr"
        Title: OC CCI Global
        Style: OC_CCI
        
Styles:
  - Identifier: S2L2A
    ColorMappings:
      B02:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B03:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B04:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      B08:
        ColorBar: "Greys_r"
        ValueRange: [0., 0.25]
      rgb:
        Red:
          Variable: B04
          ValueRange: [0., 0.25]
        Green:
          Variable: B03
          ValueRange: [0., 0.25]
        Blue:
          Variable: B02
          ValueRange: [0., 0.25]
  - Identifier: CMEMS
    ColorMappings:
      CHL_mean:
        ColorBar: "viridis"
        ValueRange: [0., 8.]
  - Identifier: OC_CCI
    ColorMappings:
      OC-CCI_chlor_a:
        ColorBar: "viridis"
        ValueRange: [0., 8.]

ServiceProvider:
  ProviderName: Brockmann Consult GmbH
  ProviderSite: https://www.brockmann-consult.de
  ServiceContact:
    IndividualName: Konstantin Ntokas
    PositionName: Software Engineer
    ContactInfo:
      Address:
        DeliveryPoint: Chrysanderstr. 1
        City: Hamburg
        AdministrativeArea: Hamburg
        PostalCode: 21029
        Country: Germany
        ElectronicMailAddress: info@brockmann-consult.de